[phases.setup]
nixPkgs = ["nodejs"]

[phases.setup.env]
NIXPACKS_NODE_VERSION = "18"

[phases.install]
cmds = ["npm install --no-audit --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx serve -s build"
